// front-end/src/routes/school/exams/[examId]/+page.svelte
<script lang="ts">
  let { data } = $props();

  const examTypeBadge: Record<string, string> = {
    score_based: 'bg-blue-100 text-blue-700',
    multiple_choice: 'bg-green-100 text-green-700',
    rubric_based: 'bg-purple-100 text-purple-700',
    pass_fail: 'bg-amber-100 text-amber-700'
  };

  const statusBadge: Record<string, string> = {
    draft: 'bg-slate-100 text-slate-600',
    scheduled: 'bg-blue-100 text-blue-700',
    active: 'bg-green-100 text-green-700',
    closed: 'bg-amber-100 text-amber-700',
    archived: 'bg-gray-100 text-gray-500'
  };

  const submissionStatusBadge: Record<string, string> = {
    in_progress: 'bg-yellow-100 text-yellow-700',
    submitted: 'bg-blue-100 text-blue-700',
    graded: 'bg-green-100 text-green-700'
  };

  function examTypeLabel(type: string) {
    return type.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  }

  function formatDate(dt: string | null) {
    if (!dt) return '—';
    return new Date(dt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  }

  const exam = $derived(data.exam);
</script>

<svelte:head>
  <title>{exam?.title ?? 'Exam'} — GrewMe</title>
</svelte:head>

<div>
  <!-- Breadcrumb -->
  <nav class="text-sm text-text-muted mb-4">
    <a href="/school/exams" class="hover:text-text">Exams</a>
    <span class="mx-2">›</span>
    <span class="text-text">{exam?.title}</span>
  </nav>

  <!-- Exam Header -->
  <div class="bg-surface rounded-xl border border-slate-100 p-6 mb-6">
    <div class="flex items-start justify-between flex-wrap gap-4">
      <div>
        <div class="flex items-center gap-3 mb-2">
          <h1 class="text-2xl font-bold text-text">{exam?.title}</h1>
          <span class="text-sm px-2.5 py-1 rounded-full font-medium {examTypeBadge[exam?.examType ?? ''] ?? 'bg-slate-100 text-slate-700'}">
            {examTypeLabel(exam?.examType ?? '')}
          </span>
        </div>
        {#if exam?.description}
          <p class="text-text-muted mb-3">{exam?.description}</p>
        {/if}
        <p class="text-sm text-text-muted">
          <a href="/school/curriculum/{exam?.topic?.subject?.id}" class="hover:text-text">{exam?.topic?.subject?.name}</a>
          <span class="mx-1">›</span>
          <a href="/school/curriculum/{exam?.topic?.subject?.id}/{exam?.topic?.id}" class="hover:text-text">{exam?.topic?.name}</a>
        </p>
      </div>
      <div class="flex flex-col gap-1 text-sm text-text-muted text-right">
        {#if exam?.maxScore}
          <span>Max score: <strong class="text-text">{exam?.maxScore}</strong></span>
        {/if}
        {#if exam?.durationMinutes}
          <span>Duration: <strong class="text-text">{exam?.durationMinutes} min</strong></span>
        {/if}
      </div>
    </div>
  </div>

  <!-- Questions / Criteria -->
  {#if exam?.examType === 'rubric_based' && exam?.rubricCriteria?.length > 0}
    <div class="bg-surface rounded-xl border border-slate-100 p-6 mb-6">
      <h2 class="text-lg font-semibold text-text mb-4">Rubric Criteria</h2>
      <div class="space-y-3">
        {#each exam.rubricCriteria as criterion}
          <div class="flex items-start justify-between p-3 bg-slate-50 rounded-lg">
            <div>
              <p class="font-medium text-text">{criterion.name}</p>
              {#if criterion.description}
                <p class="text-sm text-text-muted mt-0.5">{criterion.description}</p>
              {/if}
            </div>
            <span class="text-sm font-medium text-text ml-4">{criterion.maxScore} pts</span>
          </div>
        {/each}
      </div>
    </div>
  {:else if exam?.examQuestions?.length > 0}
    <div class="bg-surface rounded-xl border border-slate-100 p-6 mb-6">
      <h2 class="text-lg font-semibold text-text mb-4">Questions</h2>
      <div class="space-y-3">
        {#each exam.examQuestions as question}
          <div class="p-3 bg-slate-50 rounded-lg">
            <div class="flex items-start justify-between">
              <p class="text-text">{question.position}. {question.questionText}</p>
              <span class="text-sm font-medium text-text-muted ml-4 whitespace-nowrap">{question.points} pts</span>
            </div>
            {#if question.options?.length}
              <ul class="mt-2 space-y-1">
                {#each question.options as option}
                  <li class="text-sm text-text-muted pl-4">• {option}</li>
                {/each}
              </ul>
            {/if}
          </div>
        {/each}
      </div>
    </div>
  {/if}

  <!-- Assigned Classrooms -->
  <h2 class="text-xl font-semibold text-text mb-4">Assigned Classrooms</h2>

  {#if !exam?.classroomExams || exam.classroomExams.length === 0}
    <div class="text-center py-8 text-text-muted mb-6">
      <p>This exam hasn't been assigned to any classrooms yet.</p>
    </div>
  {:else}
    <div class="space-y-4 mb-6">
      {#each exam.classroomExams as ce}
        <div class="bg-surface rounded-xl border border-slate-100 p-5">
          <div class="flex items-center justify-between mb-3">
            <h3 class="font-semibold text-text">{ce.classroom.name}</h3>
            <span class="text-xs px-2 py-0.5 rounded-full font-medium {statusBadge[ce.status] ?? 'bg-slate-100 text-slate-600'}">
              {ce.status}
            </span>
          </div>
          <div class="flex gap-4 text-xs text-text-muted mb-4">
            {#if ce.scheduledAt}
              <span>Scheduled: {formatDate(ce.scheduledAt)}</span>
            {/if}
            {#if ce.dueAt}
              <span>Due: {formatDate(ce.dueAt)}</span>
            {/if}
          </div>

          <!-- Submissions -->
          {#if ce.examSubmissions?.length > 0}
            <div class="border-t border-slate-100 pt-3">
              <p class="text-xs font-medium text-text-muted uppercase tracking-wide mb-2">
                Submissions ({ce.examSubmissions.length})
              </p>
              <div class="space-y-2">
                {#each ce.examSubmissions as submission}
                  <div class="flex items-center justify-between text-sm">
                    <span class="text-text">{submission.student.name}</span>
                    <div class="flex items-center gap-3">
                      {#if submission.score !== null}
                        <span class="text-text-muted">{submission.score} pts</span>
                      {/if}
                      {#if submission.passed !== null}
                        <span class="text-xs {submission.passed ? 'text-green-600' : 'text-red-600'}">
                          {submission.passed ? 'Passed' : 'Failed'}
                        </span>
                      {/if}
                      <span class="text-xs px-2 py-0.5 rounded-full {submissionStatusBadge[submission.status] ?? 'bg-slate-100 text-slate-600'}">
                        {submission.status.replace('_', ' ')}
                      </span>
                    </div>
                  </div>
                {/each}
              </div>
            </div>
          {:else}
            <p class="text-sm text-text-muted">No submissions yet.</p>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>

// mobile/app/(app)/teacher/exams/[examId]/index.tsx
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, router } from 'expo-router';
import LoadingState from '../../../../../src/components/LoadingState';
import ErrorState from '../../../../../src/components/ErrorState';
import { useExamDetailQuery } from '../../../../../src/graphql/generated/graphql';

function formatDate(dateStr: string | null | undefined): string {
  if (!dateStr) return '--';
  const d = new Date(dateStr);
  return d.toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

function statusColor(status: string): string {
  switch (status) {
    case 'ACTIVE':
      return '#4CAF50';
    case 'DRAFT':
      return '#FF9800';
    case 'CLOSED':
      return '#9E9E9E';
    case 'SUBMITTED':
      return '#2196F3';
    case 'GRADED':
      return '#4CAF50';
    case 'IN_PROGRESS':
      return '#FF9800';
    case 'NOT_STARTED':
      return '#9E9E9E';
    default:
      return '#666';
  }
}

export default function ExamDetailScreen() {
  const { examId } = useLocalSearchParams<{ examId: string }>();

  const { data, loading, error, refetch } = useExamDetailQuery({
    variables: { id: examId ?? '' },
    skip: !examId,
  });

  if (loading) return <LoadingState message="Loading exam..." />;
  if (error) return <ErrorState message={error.message} onRetry={refetch} />;

  const exam = data?.exam;

  if (!exam) {
    return (
      <View style={styles.emptyContainer} testID="exam-not-found">
        <Text style={styles.emptyText}>Exam not found</Text>
      </View>
    );
  }

  const questions = [...(exam.examQuestions ?? [])].sort(
    (a, b) => a.position - b.position,
  );
  const criteria = [...(exam.rubricCriteria ?? [])].sort(
    (a, b) => a.position - b.position,
  );
  const classroomExams = exam.classroomExams ?? [];

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.scrollContent}
      testID="exam-detail-screen"
    >
      {/* Header */}
      <View style={styles.headerSection}>
        <Text style={styles.breadcrumb}>
          {exam.topic.subject?.name ?? 'Subject'} &gt; {exam.topic.name}
        </Text>
        <Text style={styles.header}>{exam.title}</Text>
        {exam.description ? (
          <Text style={styles.description}>{exam.description}</Text>
        ) : null}

        <View style={styles.metaRow}>
          <View style={styles.metaChip}>
            <Text style={styles.metaChipText}>
              {exam.examType.replace('_', ' ')}
            </Text>
          </View>
          {exam.maxScore ? (
            <Text style={styles.metaText}>{exam.maxScore} pts</Text>
          ) : null}
          {exam.durationMinutes ? (
            <Text style={styles.metaText}>{exam.durationMinutes} min</Text>
          ) : null}
        </View>
      </View>

      {/* Questions (MULTIPLE_CHOICE) */}
      {questions.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Questions</Text>
          {questions.map((q) => (
            <View key={q.id} style={styles.card} testID={`question-${q.id}`}>
              <Text style={styles.cardTitle}>
                Q{q.position}. {q.questionText}
              </Text>
              <Text style={styles.cardMeta}>{q.points} pts</Text>
            </View>
          ))}
        </View>
      )}

      {/* Rubric Criteria */}
      {criteria.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Rubric Criteria</Text>
          {criteria.map((c) => (
            <View key={c.id} style={styles.card} testID={`criteria-${c.id}`}>
              <View style={styles.cardRow}>
                <Text style={styles.cardTitle}>{c.name}</Text>
                <Text style={styles.cardMeta}>Max: {c.maxScore}</Text>
              </View>
              {c.description ? (
                <Text style={styles.cardDescription}>{c.description}</Text>
              ) : null}
            </View>
          ))}
        </View>
      )}

      {/* Classroom Assignments */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Classroom Assignments</Text>
        {classroomExams.length === 0 ? (
          <Text style={styles.emptySection} testID="assignments-empty">
            Not assigned to any classroom yet.
          </Text>
        ) : (
          classroomExams.map((ce) => {
            const submissions = ce.examSubmissions ?? [];
            const submittedCount = submissions.filter(
              (s) => s.status === 'SUBMITTED' || s.status === 'GRADED',
            ).length;
            const gradedCount = submissions.filter(
              (s) => s.status === 'GRADED',
            ).length;

            return (
              <View
                key={ce.id}
                style={styles.assignmentCard}
                testID={`assignment-${ce.id}`}
              >
                <View style={styles.assignmentHeader}>
                  <Text style={styles.classroomName}>
                    {ce.classroom.name}
                  </Text>
                  <View
                    style={[
                      styles.statusBadge,
                      { backgroundColor: statusColor(ce.status) },
                    ]}
                  >
                    <Text style={styles.statusBadgeText}>{ce.status}</Text>
                  </View>
                </View>

                <View style={styles.dateRow}>
                  {ce.scheduledAt ? (
                    <Text style={styles.dateText}>
                      Scheduled: {formatDate(ce.scheduledAt)}
                    </Text>
                  ) : null}
                  {ce.dueAt ? (
                    <Text style={styles.dateText}>
                      Due: {formatDate(ce.dueAt)}
                    </Text>
                  ) : null}
                </View>

                <Text style={styles.summaryText}>
                  {submittedCount}/{submissions.length} submitted{' '}
                  &middot; {gradedCount}/{submissions.length} graded
                </Text>

                {/* Submissions */}
                {submissions.length > 0 && (
                  <View style={styles.submissionsList}>
                    {submissions.map((sub) => (
                      <Pressable
                        key={sub.id}
                        style={styles.submissionRow}
                        onPress={() =>
                          router.push(
                            `/(app)/teacher/exams/${examId}/grade/${sub.id}`,
                          )
                        }
                        testID={`submission-${sub.id}`}
                      >
                        <View style={styles.submissionInfo}>
                          <Text style={styles.studentName}>
                            {sub.student.name}
                          </Text>
                          <View
                            style={[
                              styles.submissionBadge,
                              {
                                backgroundColor: statusColor(sub.status),
                              },
                            ]}
                          >
                            <Text style={styles.submissionBadgeText}>
                              {sub.status.replace('_', ' ')}
                            </Text>
                          </View>
                        </View>
                        <View style={styles.submissionMeta}>
                          {sub.score != null ? (
                            <Text style={styles.scoreText}>
                              {sub.score}/{exam.maxScore ?? '?'}
                            </Text>
                          ) : null}
                          <Ionicons
                            name="chevron-forward"
                            size={16}
                            color="#CCC"
                          />
                        </View>
                      </Pressable>
                    ))}
                  </View>
                )}
              </View>
            );
          })
        )}
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  scrollContent: {
    paddingBottom: 32,
  },
  headerSection: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  breadcrumb: {
    fontSize: 13,
    color: '#999',
    marginBottom: 4,
  },
  header: {
    fontSize: 22,
    fontWeight: '700',
    color: '#333',
  },
  description: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 10,
  },
  metaChip: {
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  metaChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4CAF50',
    textTransform: 'capitalize',
  },
  metaText: {
    fontSize: 13,
    color: '#888',
  },
  section: {
    paddingHorizontal: 16,
    marginTop: 16,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#333',
    marginBottom: 10,
  },
  emptySection: {
    fontSize: 13,
    color: '#999',
    fontStyle: 'italic',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 1,
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  cardDescription: {
    fontSize: 13,
    color: '#666',
    marginTop: 4,
  },
  cardMeta: {
    fontSize: 12,
    color: '#999',
    marginTop: 4,
  },
  assignmentCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 1,
  },
  assignmentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  classroomName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  statusBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  dateRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 6,
  },
  dateText: {
    fontSize: 12,
    color: '#888',
  },
  summaryText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '500',
    marginBottom: 8,
  },
  submissionsList: {
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
    paddingTop: 8,
  },
  submissionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  submissionInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  studentName: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  submissionBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  submissionBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  submissionMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  scoreText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333',
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  emptyText: {
    fontSize: 16,
    color: '#666',
  },
});
